name: rag-bot-test
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.7.14
  - faiss=1.9.0
  - faiss-cpu=1.9.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=20.1.8
  - libexpat=2.7.1
  - libfaiss=1.9.0
  - libffi=3.4.6
  - libgfortran=5.0.0
  - libgfortran5=14.2.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libopenblas=0.3.30
  - libsqlite=3.50.3
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - ncurses=6.5
  - numpy=1.26.4
  - openssl=3.5.1
  - packaging=25.0
  - pip=25.1.1
  - python=3.10.18
  - python_abi=3.10
  - readline=8.2
  - setuptools=80.9.0
  - tk=8.6.13
  - tzdata=2025b
  - wheel=0.45.1
  - pip:
      - pymupdf==1.26.3
      - sentence-transformers
      - rank-bm25
      - langchain-community
      - langdetect
      - llama-cpp-python
      - gradio
