name: rag-bot-test
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2
  - ca-certificates
  - faiss
  - faiss-cpu
  - libblas
  - libcblas
  - libcxx
  - libexpat
  - libfaiss
  - libffi
  - libgfortran
  - libgfortran5
  - liblapack
  - liblzma
  - libopenblas
  - libsqlite
  - libzlib
  - llvm-openmp
  - ncurses
  - numpy
  - openssl
  - packaging
  - pip
  - python
  - python_abi
  - readline
  - setuptools
  - tk
  - tzdata
  - wheel
  - pip:
      - pymupdf
      - sentence-transformers
      - rank-bm25
      - langchain-community
      - langdetect
      - llama-cpp-python
      - gradio
